version: '3.9'

services:
  web:
    build: .
    working_dir: /code/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --reload

    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"