version: '3.9'

services:
  web:
    build: .
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --reload

    volumes:
      - ./app:/code/app
    ports:
      - "80:80"
    depends_on:
      - redis

  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"